#%RAML 1.0 NamedExample
value:
  -
    cid: 100
    cname: Haben
    lname: Abera
    street: Merill road
    city: Jacksonville
    state: Fl
    zip: 32233
  -
    cid: 200
    cname: Yodit
    lname: Gezahegn
    street: Normandy
    city: Jacksonville
    state: Fl
    zip: 32222